// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
        tag="Nuestra Filosofía"
        quote="La presencia digital ya no es opcional; es la base del comercio moderno. Unimos la visión de tu marca con la realidad digital de tus clientes."
        author="Elena Vance"
        role="Fundadora, Meridian Agency"
        imageSrc="http://img.b2bpic.net/free-photo/diverse-business-colleagues-with-digital-tablet-discussing-project_74855-1778.jpg"
        textAnimation="fade"
      />
        </SectionErrorBoundary>
      </div>
  );
}
