// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutTestimonial
          tag="Our Philosophy"
          quote="Digital presence is no longer optional; it's the foundation of modern commerce. We bridge the gap between your brand's vision and your customers' digital reality."
          author="Elena Vance"
          role="Founder, Meridian Agency"
          imageSrc="http://img.b2bpic.net/free-photo/diverse-business-colleagues-with-digital-tablet-discussing-project_74855-1778.jpg"
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
