// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="Contacto"
          text="¿Listo para potenciar tu presencia digital? Construyamos algo grande juntos."
          primaryButton={{
            text: "Agendar Consulta",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Enviar Email",
            href: "mailto:hola@monix.agency",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
