// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "expertise" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ExpertiseSection(): React.JSX.Element {
  return (
    <div id="expertise" data-section="expertise">
        <SectionErrorBoundary name="expertise">
              <FeaturesImageBento
        tag="Sectores"
        title="Soluciones para cada sector"
        description="Nos especializamos en soluciones web de alta conversión para diversas industrias."
        items={[{"imageSrc":"http://img.b2bpic.net/free-photo/wine-glass_1203-2992.jpg","description":"Menús interactivos y sistemas de reserva que aumentan la rotación de mesas.","title":"Restaurantes"},{"title":"Clínicas","imageSrc":"http://img.b2bpic.net/free-photo/living-room-with-white-couch-coffee-table_188544-18668.jpg","description":"Portales de pacientes y reserva de citas segura para el sector salud."},{"title":"Gimnasios","imageSrc":"http://img.b2bpic.net/free-photo/still-life-gym-equipment_23-2148197730.jpg","description":"Plataformas de membresía y gestión de clases para centros deportivos."},{"title":"Comercios","imageSrc":"http://img.b2bpic.net/free-photo/turquoise-wooden-table-front-shopping-mall_23-2147907236.jpg","description":"Tiendas online optimizadas para maximizar tus ventas."},{"description":"Gestión de citas previas y catálogos de servicios exclusivos.","title":"Peluquerías y Estética","imageSrc":"http://img.b2bpic.net/free-photo/beautiful-smiling-woman-with-makeup-brushes_23-2148113369.jpg"},{"description":"Optimización de presencia local y pedidos digitales.","imageSrc":"http://img.b2bpic.net/free-photo/table-set-dinning-table_1339-6425.jpg","title":"Cafeterías"},{"description":"Reserva de puestos y gestión de espacios de trabajo compartidos.","imageSrc":"http://img.b2bpic.net/free-photo/asian-woman-with-headset-using-computer_482257-120429.jpg","title":"Co-working"}]}
        textAnimation="slide-up"
      />
        </SectionErrorBoundary>
      </div>
  );
}
