// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Knowledge Hub"
          title="Frequently asked questions"
          description="Everything you need to know about working with us."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "How long does a typical project take?",
                  answer: "Most web builds take between 4-8 weeks depending on complexity.",
                },
                {
                  question: "Do you offer maintenance?",
                  answer: "Yes, we provide ongoing maintenance and security support packages.",
                },
              ],
            },
            {
              name: "Process",
              items: [
                {
                  question: "How do we get started?",
                  answer: "Simply fill out our contact form and we'll schedule a discovery call.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
