// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTabbedAccordion from '@/components/sections/faq/FaqTabbedAccordion';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqTabbedAccordion
          tag="Preguntas Frecuentes"
          title="Resolvemos tus dudas"
          description="Todo lo que necesitas saber sobre cómo trabajamos."
          categories={[
            {
              name: "General",
              items: [
                {
                  question: "¿Cuánto tiempo se tarda en desarrollar una web?",
                  answer: "La mayoría de los proyectos se completan en 2 a 4 semanas según su complejidad.",
                },
                {
                  question: "¿Ofrecen mantenimiento continuo?",
                  answer: "Sí, disponemos de planes de mantenimiento, seguridad y optimización periódica.",
                },
              ],
            },
            {
              name: "Proceso",
              items: [
                {
                  question: "¿Cómo empezamos a trabajar?",
                  answer: "Solo tienes que rellenar el formulario de contacto y agendaremos una llamada inicial.",
                },
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
