// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBrand from '@/components/sections/hero/HeroBrand';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroBrand
        brand="Monix Agency"
        description="Diseñamos y desarrollamos páginas web de alto impacto para restaurantes, clínicas, gimnasios y comercios. Potenciamos la presencia digital y la conversión de tu negocio."
        primaryButton={{"text":"Empezar Proyecto","href":"#contact"}}
        secondaryButton={{"href":"#expertise","text":"Ver Sectoresectores"}}
        imageSrc="http://img.b2bpic.net/free-photo/optical-fiber-background_23-2149301562.jpg"
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
