// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Results"
          title="By the numbers"
          description="Measurable impact on every project we take on."
          metrics={[
            {
              value: "150+",
              description: "Projects Delivered",
            },
            {
              value: "40%",
              description: "Average Revenue Growth",
            },
            {
              value: "95%",
              description: "Client Retention Rate",
            },
            {
              value: "24h",
              description: "Average Support Response",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
