// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsSimpleCards
          tag="Resultados"
          title="En cifras"
          description="Impacto medible en cada proyecto que desarrollamos."
          metrics={[
            {
              value: "150+",
              description: "Proyectos Entregados",
            },
            {
              value: "40%",
              description: "Crecimiento Medio en Ingresos",
            },
            {
              value: "95%",
              description: "Tasa de Retención de Clientes",
            },
            {
              value: "24h",
              description: "Respuesta Media de Soporte",
            },
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
