// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialColumnMarqueeCards from '@/components/sections/testimonial/TestimonialColumnMarqueeCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialColumnMarqueeCards
        tag="Prueba Social"
        title="Casos de Éxito"
        description="Nuestros clientes respaldan los resultados obtenidos."
        testimonials={[{"imageSrc":"http://img.b2bpic.net/free-photo/portrait-happy-businessman-with-crossed-arms_23-2147955274.jpg","quote":"Monix Agency aumentó nuestras reservas de mesas un 40% en solo dos meses.","role":"Propietario de Restaurante","name":"David M."},{"quote":"Un portal de pacientes impecables. La mejor inversión que hemos hecho este año.","name":"Sara P.","imageSrc":"http://img.b2bpic.net/free-photo/smiling-beautiful-corporate-woman-beige-suit-standing-street-city-with-wireless-headphones_1258-194021.jpg","role":"Directora de Clínica"},{"quote":"Diseño moderno y fácil de usar. A nuestros socios les encanta la nueva app.","name":"Marcos L.","imageSrc":"http://img.b2bpic.net/free-photo/young-man-business-worker-using-vr-glasses-working-office_839833-10645.jpg","role":"Fundador de Gimnasio"},{"imageSrc":"http://img.b2bpic.net/free-photo/smiling-beautiful-middle-aged-business-woman_1262-3085.jpg","role":"Propietaria de Boutique","name":"Elena R.","quote":"Las tasas de conversión se han duplicado desde que lanzamos con Monix Agency."},{"name":"Lucas F.","quote":"La presencia local que construyeron ha atraído a muchos más clientes físicos.","imageSrc":"http://img.b2bpic.net/free-photo/portrait-man-black-suit_23-2148401442.jpg","role":"Propietario de Cafetería"}]}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
